# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  observabilityapp:
    image: observabilityapp
    build:
      context: .
      dockerfile: Observability.App/Dockerfile
    ports:
      - 5251:5251
